# %%
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df_bruta = pd.read_csv("data/Producao_Bruta.csv", encoding="latin1")
df_benef = pd.read_csv("data/Producao_Beneficiada.csv", encoding="latin1")
def str_to_float(x:str):
    x = (x.replace(" ", "")
          .replace(",", ".")
          .replace("\xa0","")
        )
    return float(x)

df_bruta["Quantidade Produção - Minério ROM (t)"] = df_bruta["Quantidade Produção - Minério ROM (t)"].apply(str_to_float)
df_bruta["Quantidade Contido"] = df_bruta["Quantidade Contido"].apply(str_to_float)
df_bruta["Quantidade Venda (t)"] = df_bruta["Quantidade Venda (t)"].apply(str_to_float)
df_bruta["Valor Venda (R$)"] = df_bruta["Valor Venda (R$)"].apply(str_to_float)
df_bruta["Quantidade Transformação / Consumo / Utilização (t)"] = df_bruta["Quantidade Transformação / Consumo / Utilização (t)"].apply(str_to_float)
df_bruta["Valor Transformação / Consumo / Utilização nesta mina (R$)"] = df_bruta["Valor Transformação / Consumo / Utilização nesta mina (R$)"].apply(str_to_float)
df_bruta["Quantidade Transferência para Transformação / Utilização / Consumo (t)"] = df_bruta["Quantidade Transferência para Transformação / Utilização / Consumo (t)"].apply(str_to_float)
df_bruta["Valor Transferência para Transformação / Utilização / Consumo (R$)"] = df_bruta["Valor Transferência para Transformação / Utilização / Consumo (R$)"].apply(str_to_float)

df_benef["Quantidade Produção"] = df_benef["Quantidade Produção"].apply(str_to_float)
df_benef["Quantidade Consumo/Utilização na Usina"] = df_benef["Quantidade Consumo/Utilização na Usina"].apply(str_to_float)
df_benef["Valor Consumo / Utilização na Usina (R$)"] = df_benef["Valor Consumo / Utilização na Usina (R$)"].apply(str_to_float)
df_benef["Quantidade Contido"] = df_benef["Quantidade Contido"].apply(str_to_float)
df_benef["Quantidade Venda"] = df_benef["Quantidade Venda"].apply(str_to_float)
df_benef["Valor Venda (R$)"] = df_benef["Valor Venda (R$)"].apply(str_to_float)
df_benef["Quantidade Transferência para Transformação / Utilização / Consumo"] = df_benef["Quantidade Transferência para Transformação / Utilização / Consumo"].apply(str_to_float)
df_benef["Valor Transferência para Transformação / Utilização / Consumo (R$)"] = df_benef["Valor Transferência para Transformação / Utilização / Consumo (R$)"].apply(str_to_float)
# %%
plt.figure(figsize=(10,8))
sns.boxplot(data=df_bruta, x="Classe Substância", y="Valor Venda (R$)", color='indianred')
plt.yscale('log')
plt.xlabel('Classe Substância', fontsize=12, fontweight='bold')
plt.ylabel('Valor Venda (R$)', fontsize=12, fontweight='bold')
plt.title("Distribuição de Valor por Classe (Escala Logarítmica)", fontsize=14, fontweight='bold')
plt.xticks(rotation=0)
plt.show()
# %%
plt.figure(figsize=(10,8))
sns.boxplot(data=df_benef, x="Classe Substância", y="Valor Venda (R$)", color='gold')
plt.yscale('log')
plt.xlabel('Classe Substância', fontsize=12, fontweight='bold')
plt.ylabel('Valor Venda (R$)', fontsize=12, fontweight='bold')
plt.title("Distribuição de Valor por Classe (Escala Logarítmica)", fontsize=14, fontweight='bold')
plt.xticks(rotation=0)
plt.show()

# %%
plt.figure(figsize=(10,8))
mineral_counts = df_bruta['Classe Substância'].value_counts()
mineral_counts.plot(kind='bar', color='crimson', edgecolor='black', alpha=1)
plt.title('Distribuição dos Tipos de Minérios', fontsize=14, fontweight='bold')
plt.xlabel('Grupo das Substâncias', fontsize=12, fontweight='bold')
plt.ylabel('Número de Substâncias', fontsize=12, fontweight='bold')
plt.xticks(rotation=0)
plt.grid(axis='y', alpha=0.5, color='black')
plt.show()

# %%
plt.figure(figsize=(10,8))
mineral_counts = df_bruta['Substância Mineral'].value_counts()
mineral_counts.plot(kind='bar', color='darkorchid', edgecolor='black', alpha=1)
plt.title('Distribuição das Substâncias Minerais', fontsize=14, fontweight='bold')
plt.xlabel('Nome das Substâncias', fontsize=12, fontweight='bold')
plt.ylabel('Número de Substâncias', fontsize=12, fontweight='bold')
plt.xticks(rotation=90)
plt.grid(axis='y', alpha=0.5, color='black')
plt.show()
# %%
plt.figure(figsize=(12, 6))
ano_counts = df_bruta['Ano base'].value_counts().sort_index()
ano_counts.plot(kind='bar', color='darkslateblue', edgecolor='black', alpha=0.8)
plt.title('Número de Registros por Ano', fontsize=14, fontweight='bold')
plt.xlabel('Anos')
plt.ylabel('Número de Registros')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', alpha=0.5, color='black')
plt.tight_layout()
plt.show()
# %%
plt.figure(figsize=(12, 6))
ano_counts = df_bruta['UF'].value_counts().sort_index()
ano_counts.plot(kind='bar', color='burlywood', edgecolor='black', alpha=0.8)
plt.title('Número de Registros por Estado do Brasil', fontsize=14, fontweight='bold')
plt.xlabel('Estados do Brasil')
plt.ylabel('Número de Registros')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', alpha=0.5, color='black')
plt.tight_layout()
plt.show()

# %%
plt.figure(figsize=(10,8))
mineral_counts = df_benef['Classe Substância'].value_counts()
mineral_counts.plot(kind='bar', color='navy', edgecolor='black', alpha=1)
plt.title('Distribuição dos Tipos de Minérios', fontsize=14, fontweight='bold')
plt.xlabel('Grupo das Substâncias', fontsize=12, fontweight='bold')
plt.ylabel('Número de Substâncias', fontsize=12, fontweight='bold')
plt.xticks(rotation=0)
plt.grid(axis='y', alpha=0.5, color='black')
plt.show()

# %%
plt.figure(figsize=(10,8))
mineral_counts = df_benef['Substância Mineral'].value_counts()
mineral_counts.plot(kind='bar', color='teal', edgecolor='black', alpha=1)
plt.title('Distribuição das Substâncias Minerais', fontsize=14, fontweight='bold')
plt.xlabel('Nome das Substâncias', fontsize=12, fontweight='bold')
plt.ylabel('Número de Substâncias', fontsize=12, fontweight='bold')
plt.xticks(rotation=90)
plt.grid(axis='y', alpha=0.5, color='black')
plt.show()
# %%
plt.figure(figsize=(12, 6))
ano_counts = df_benef['Ano base'].value_counts().sort_index()
ano_counts.plot(kind='bar', color='dodgerblue', edgecolor='black', alpha=0.8)
plt.title('Número de Registros por Ano', fontsize=14, fontweight='bold')
plt.xlabel('Anos')
plt.ylabel('Número de Registros')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', alpha=0.5, color='black')
plt.tight_layout()
plt.show()
# %%
plt.figure(figsize=(12, 6))
ano_counts = df_benef['UF'].value_counts().sort_index()
ano_counts.plot(kind='bar', color='limegreen', edgecolor='black', alpha=0.8)
plt.title('Número de Registros por Estado do Brasil', fontsize=14, fontweight='bold')
plt.xlabel('Estados do Brasil')
plt.ylabel('Número de Registros')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', alpha=0.5, color='black')
plt.tight_layout()
plt.show()